Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -52,6 +52,7 @@ jobs:
         run: |
           docker-compose -f docker-compose.test.yml exec -T db sh -c "mysqldump -h mysql -P 3306 -u root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE > /tmp/db-dump.sql" || (echo "mysqldump command failed" && docker-compose -f docker-compose.test.yml logs db && exit 1)
           docker cp mysql:/tmp/db-dump.sql ./db-dump.sql
+          docker-compose -f docker-compose.test.yml exec -T db sh -c "mysql -h mysql -P 3306 -u root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE -e 'SELECT * FROM users;'" || (echo "SELECT command failed" && docker-compose -f docker-compose.test.yml logs db && exit 1)
 
       - name: Set executable permission for gradlew
         run: chmod +x ./api/crewsync/gradlew
